sonar.projectKey=Ecommerce_Product_Recommender
sonar.projectName=Ecommerce Product Recommender
sonar.sources=.
sonar.exclusions=venv/**,.venv/**,**/__pycache__/**,build/**,dist/**,**/*.yml,**/*.yaml,**/*.css,**/*.html,Data/**
sonar.python.version=3.11
# (si tu ajoutes tests + couverture pytest)
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
