# --- Sonar basics (ADAPTE ces 2 lignes) ---
sonar.projectKey=ridabayi_E-Commerce_IA_Agent_for_Product_Recommendation
sonar.organization=ridabayi

# --- Python ---
sonar.python.version=3.11

# --- Sources / exclusions ---
sonar.sources=.
sonar.exclusions=venv/**,.venv/**,**/__pycache__/**,**/*.egg-info/**,.github/**,.vscode/**

# --- Tests & coverage (pytest -> coverage.xml) ---
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml


